# 基础路径配置
delivery_car: S:\po-assets\gallery\delivery

# 指令映射关系 (指令: 目标路径)
mappings:
  check: S:\po-assets\gallery\delivery
  ###################################### 二次元世界 #############################################
  # 原神 Genshin Impact ########################################################################
  ## 璃月
  甘雨: S:\po-assets\gallery\二次元\原神\甘雨
  ganyu: S:\po-assets\gallery\二次元\原神\甘雨
  Ganyu: S:\po-assets\gallery\二次元\原神\甘雨
  椰羊: S:\po-assets\gallery\二次元\原神\甘雨
  王小美: S:\po-assets\gallery\二次元\原神\甘雨
  ## 稻妻
  心海: S:\po-assets\gallery\二次元\原神\珊瑚宫心海
  珊瑚宫心海: S:\po-assets\gallery\二次元\原神\珊瑚宫心海
  ## 须弥
  nahida: S:\po-assets\gallery\二次元\原神\须弥\纳西妲
  Nahida: S:\po-assets\gallery\二次元\原神\须弥\纳西妲
  纳西妲: S:\po-assets\gallery\二次元\原神\须弥\纳西妲
  草神: S:\po-assets\gallery\二次元\原神\须弥\纳西妲
  小吉祥草王: S:\po-assets\gallery\二次元\原神\须弥\纳西妲
  妮露: S:\po-assets\gallery\二次元\原神\须弥\妮露
  nilou: S:\po-assets\gallery\二次元\原神\须弥\妮露
  Nilou: S:\po-assets\gallery\二次元\原神\须弥\妮露
  ## 枫丹
  芙宁娜: S:\po-assets\gallery\二次元\原神\枫丹\芙宁娜
  芙卡洛斯: S:\po-assets\gallery\二次元\原神\枫丹\芙宁娜
  furina: S:\po-assets\gallery\二次元\原神\枫丹\芙宁娜
  focalors: S:\po-assets\gallery\二次元\原神\枫丹\芙宁娜
  Furina: S:\po-assets\gallery\二次元\原神\枫丹\芙宁娜
  Focalors: S:\po-assets\gallery\二次元\原神\枫丹\芙宁娜
  希格雯: S:\po-assets\gallery\二次元\原神\枫丹\希格雯
  ## 纳塔
  mualani: S:\po-assets\gallery\二次元\原神\纳塔\玛拉妮
  Mualani: S:\po-assets\gallery\二次元\原神\纳塔\玛拉妮
  玛拉妮: S:\po-assets\gallery\二次元\原神\纳塔\玛拉妮
  麻辣妮: S:\po-assets\gallery\二次元\原神\纳塔\玛拉妮
  麻辣妮儿: S:\po-assets\gallery\二次元\原神\纳塔\玛拉妮
  ## 挪德卡莱
  columbina: S:\po-assets\gallery\二次元\原神\哥伦比娅
  Columbina: S:\po-assets\gallery\二次元\原神\哥伦比娅
  哥伦比娅: S:\po-assets\gallery\二次元\原神\哥伦比娅

  # 蔚蓝档案 Blue Archive #########################################################################
  BA: S:\po-assets\gallery\二次元\蔚蓝档案
  ba: S:\po-assets\gallery\二次元\蔚蓝档案
  Ba: S:\po-assets\gallery\二次元\蔚蓝档案
  ## 沙勒
  阿洛娜: S:\po-assets\gallery\二次元\蔚蓝档案\沙勒\阿洛娜
  Arona: S:\po-assets\gallery\二次元\蔚蓝档案\沙勒\阿洛娜
  arona: S:\po-assets\gallery\二次元\蔚蓝档案\沙勒\阿洛娜
  普拉娜: S:\po-assets\gallery\二次元\蔚蓝档案\沙勒\普拉娜
  plana: S:\po-assets\gallery\二次元\蔚蓝档案\沙勒\普拉娜
  Plana: S:\po-assets\gallery\二次元\蔚蓝档案\沙勒\普拉娜

  ## 阿拜多斯高级中学
  星野: S:\po-assets\gallery\二次元\蔚蓝档案\阿拜多斯高级中学\小鸟游星野
  小鸟游星野: S:\po-assets\gallery\二次元\蔚蓝档案\阿拜多斯高级中学\小鸟游星野
  大叔: S:\po-assets\gallery\二次元\蔚蓝档案\阿拜多斯高级中学\小鸟游星野
  hoshino: S:\po-assets\gallery\二次元\蔚蓝档案\阿拜多斯高级中学\小鸟游星野
  Hoshino: S:\po-assets\gallery\二次元\蔚蓝档案\阿拜多斯高级中学\小鸟游星野

  ## 千禧年科技学院
  ### 游戏开发部
  aris: S:\po-assets\gallery\二次元\蔚蓝档案\千禧年科技学院\游戏开发部\天童爱丽丝
  Aris: S:\po-assets\gallery\二次元\蔚蓝档案\千禧年科技学院\游戏开发部\天童爱丽丝
  天童爱丽丝: S:\po-assets\gallery\二次元\蔚蓝档案\千禧年科技学院\游戏开发部\天童爱丽丝
  花冈柚子: S:\po-assets\gallery\二次元\蔚蓝档案\千禧年科技学院\游戏开发部\花冈柚子

  ## 崔尼蒂综合学院
  seia: S:\po-assets\gallery\二次元\蔚蓝档案\崔尼蒂综合学院\茶会\百合园圣娅
  Seia: S:\po-assets\gallery\二次元\蔚蓝档案\崔尼蒂综合学院\茶会\百合园圣娅
  圣娅: S:\po-assets\gallery\二次元\蔚蓝档案\崔尼蒂综合学院\茶会\百合园圣娅
  百合园圣娅: S:\po-assets\gallery\二次元\蔚蓝档案\崔尼蒂综合学院\茶会\百合园圣娅

  ## 歌赫娜学院
  ### 风纪委员会
  日奈: S:\po-assets\gallery\二次元\蔚蓝档案\歌赫娜学院\风纪委员会\空崎日奈
  空崎日奈: S:\po-assets\gallery\二次元\蔚蓝档案\歌赫娜学院\风纪委员会\空崎日奈
  Hina: S:\po-assets\gallery\二次元\蔚蓝档案\歌赫娜学院\风纪委员会\空崎日奈
  hina: S:\po-assets\gallery\二次元\蔚蓝档案\歌赫娜学院\风纪委员会\空崎日奈
  ### 万魔殿
  枣伊吕波: S:\po-assets\gallery\二次元\蔚蓝档案\歌赫娜学院\万魔殿\枣伊吕波
  丹花伊吹: S:\po-assets\gallery\二次元\蔚蓝档案\歌赫娜学院\万魔殿\丹花伊吹
  ### 便利屋68
  佳代子: S:\po-assets\gallery\二次元\蔚蓝档案\歌赫娜学院\便利屋68\鬼方佳代子
  鬼方佳代子: S:\po-assets\gallery\二次元\蔚蓝档案\歌赫娜学院\便利屋68\鬼方佳代子
  睦月: S:\po-assets\gallery\二次元\蔚蓝档案\歌赫娜学院\便利屋68\浅黄睦月
  浅黄睦月: S:\po-assets\gallery\二次元\蔚蓝档案\歌赫娜学院\便利屋68\浅黄睦月
  Mutsuki: S:\po-assets\gallery\二次元\蔚蓝档案\歌赫娜学院\便利屋68\浅黄睦月
  mutsuki: S:\po-assets\gallery\二次元\蔚蓝档案\歌赫娜学院\便利屋68\浅黄睦月

  ## 百鬼夜行联合学院
  ### 百花缭乱纷争调停委员会
  桐生桔梗: S:\po-assets\gallery\二次元\蔚蓝档案\百鬼夜行联合学院\百花缭乱纷争调停委员会\桐生桔梗
  ### 花鸟风月部
  箭吹棕榈: S:\po-assets\gallery\二次元\蔚蓝档案\百鬼夜行联合学院\花鸟风月部\箭吹棕榈
  ### 阴阳部
  千世: S:\po-assets\gallery\二次元\蔚蓝档案\百鬼夜行联合学院\阴阳部\和乐千世
  和乐千世: S:\po-assets\gallery\二次元\蔚蓝档案\百鬼夜行联合学院\阴阳部\和乐千世
  Chise: S:\po-assets\gallery\二次元\蔚蓝档案\百鬼夜行联合学院\阴阳部\和乐千世
  chise: S:\po-assets\gallery\二次元\蔚蓝档案\百鬼夜行联合学院\阴阳部\和乐千世
  ### 节庆营运管理部
  Shizuko: S:\po-assets\gallery\二次元\蔚蓝档案\百鬼夜行联合学院\节庆营运管理部\河和静子
  shizuko: S:\po-assets\gallery\二次元\蔚蓝档案\百鬼夜行联合学院\节庆营运管理部\河和静子
  静子: S:\po-assets\gallery\二次元\蔚蓝档案\百鬼夜行联合学院\节庆营运管理部\河和静子
  河和静子: S:\po-assets\gallery\二次元\蔚蓝档案\百鬼夜行联合学院\节庆营运管理部\河和静子

  ## 山海经高级中学
  ### 玄龙门
  kiki: S:\po-assets\gallery\二次元\蔚蓝档案\山海经高级中学\玄龙门\龙华妃咲
  kisaki: S:\po-assets\gallery\二次元\蔚蓝档案\山海经高级中学\玄龙门\龙华妃咲
  Kisaki: S:\po-assets\gallery\二次元\蔚蓝档案\山海经高级中学\玄龙门\龙华妃咲
  妃咲: S:\po-assets\gallery\二次元\蔚蓝档案\山海经高级中学\玄龙门\龙华妃咲
  龙华妃咲: S:\po-assets\gallery\二次元\蔚蓝档案\山海经高级中学\玄龙门\龙华妃咲
  门主: S:\po-assets\gallery\二次元\蔚蓝档案\山海经高级中学\玄龙门\龙华妃咲
  门主大人: S:\po-assets\gallery\二次元\蔚蓝档案\山海经高级中学\玄龙门\龙华妃咲
  ### 梅花园
  kokona: S:\po-assets\gallery\二次元\蔚蓝档案\山海经高级中学\梅花园\春原心奈
  Kokona: S:\po-assets\gallery\二次元\蔚蓝档案\山海经高级中学\梅花园\春原心奈
  心奈: S:\po-assets\gallery\二次元\蔚蓝档案\山海经高级中学\梅花园\春原心奈
  春原心奈: S:\po-assets\gallery\二次元\蔚蓝档案\山海经高级中学\梅花园\春原心奈

  ## SRT特殊学园
  宫子: S:\po-assets\gallery\二次元\蔚蓝档案\SRT特殊学园\SRT RABBIT\月雪宫子
  月雪宫子: S:\po-assets\gallery\二次元\蔚蓝档案\SRT特殊学园\SRT RABBIT\月雪宫子

  ## 海兰德铁道学院
  橘光: S:\po-assets\gallery\二次元\蔚蓝档案\海兰德铁道学院\橘光&橘望
  橘望: S:\po-assets\gallery\二次元\蔚蓝档案\海兰德铁道学院\橘光&橘望
  铁道双子: S:\po-assets\gallery\二次元\蔚蓝档案\海兰德铁道学院\橘光&橘望

  ## 未知势力
  笑面教授: S:\po-assets\gallery\二次元\蔚蓝档案\未知势力\笑面教授

  # 崩坏：星穹铁道 ############################################################################
  ## 雅利洛-Ⅵ
  Clara: S:\po-assets\gallery\二次元\崩坏：星穹铁道\克拉拉
  clara: S:\po-assets\gallery\二次元\崩坏：星穹铁道\克拉拉
  克拉拉: S:\po-assets\gallery\二次元\崩坏：星穹铁道\克拉拉

  花火: S:\po-assets\gallery\二次元\崩坏：星穹铁道\花火
  Hanabi: S:\po-assets\gallery\二次元\崩坏：星穹铁道\花火
  hanabi: S:\po-assets\gallery\二次元\崩坏：星穹铁道\花火
  Sparkle: S:\po-assets\gallery\二次元\崩坏：星穹铁道\花火
  sparkle: S:\po-assets\gallery\二次元\崩坏：星穹铁道\花火
  ## 云璃
  云璃: S:\po-assets\gallery\二次元\崩坏：星穹铁道\云璃
  yunli: S:\po-assets\gallery\二次元\崩坏：星穹铁道\云璃
  Yunli: S:\po-assets\gallery\二次元\崩坏：星穹铁道\云璃
  ## 星核猎手
  银狼: S:\po-assets\gallery\二次元\崩坏：星穹铁道\星核猎手\银狼

  # 崩坏3 Honkai Impact 3rd ###############################################################
  griseo: S:\po-assets\gallery\二次元\崩坏3\格蕾修
  Griseo: S:\po-assets\gallery\二次元\崩坏3\格蕾修
  格蕾修: S:\po-assets\gallery\二次元\崩坏3\格蕾修
  # 千恋万花 ############################################################################
  Murasame: S:\po-assets\gallery\二次元\千恋万花\丛雨
  murasame: S:\po-assets\gallery\二次元\千恋万花\丛雨
  丛雨: S:\po-assets\gallery\二次元\千恋万花\丛雨
  # 千恋万花 ############################################################################
  甲铁城的卡巴内瑞: S:\po-assets\gallery\二次元\甲铁城的卡巴内瑞
  # 别当欧尼酱了！ ########################################################################
  别当: S:\po-assets\gallery\二次元\别当欧尼酱了！
  ###################################### 三次元世界 ######################################
  日本古风: S:\po-assets\gallery\三次元\日本古风
  鞍马寺: S:\po-assets\gallery\三次元\日本古风\鞍马寺
  银山温泉: S:\po-assets\gallery\三次元\日本古风\银山温泉
  日本都市: S:\po-assets\gallery\三次元\日本都市