# 基础路径配置
delivery_car: "S:/po-assets/gallery/delivery"

# 指令映射关系 (指令: 目标路径)
# 建议使用正斜杠 /，Java 在 Windows 下也能完美识别
mappings:
  ###################################### 二次元世界 ######################################
  # 原神
  ## 璃月
  甘雨: "S:/po-assets/gallery/二次元/原神/甘雨"
  ganyu: "S:/po-assets/gallery/二次元/原神/甘雨"
  Ganyu: "S:/po-assets/gallery/二次元/原神/甘雨"
  椰羊: "S:/po-assets/gallery/二次元/原神/甘雨"
  王小美: "S:/po-assets/gallery/二次元/原神/甘雨"
  ## 稻妻
  心海: "S:/po-assets/gallery/二次元/原神/珊瑚宫心海"
  珊瑚宫心海: "S:/po-assets/gallery/二次元/原神/珊瑚宫心海"
  ## 须弥
  nahida: "S:/po-assets/gallery/二次元/原神/纳西妲"
  纳西妲: "S:/po-assets/gallery/二次元/原神/纳西妲"
  草神: "S:/po-assets/gallery/二次元/原神/纳西妲"
  小吉祥草王: "S:/po-assets/gallery/二次元/原神/纳西妲"
  ## 挪德卡莱
  columbina: "S:/po-assets/gallery/二次元/原神/哥伦比娅"

  # 蔚蓝档案
  ## 沙勒
  阿洛娜: "S:/po-assets/gallery/二次元/蔚蓝档案/沙勒/阿洛娜"
  Arona: "S:/po-assets/gallery/二次元/蔚蓝档案/沙勒/阿洛娜"
  arona: "S:/po-assets/gallery/二次元/蔚蓝档案/沙勒/阿洛娜"
  普拉娜: "S:/po-assets/gallery/二次元/蔚蓝档案/沙勒/普拉娜"
  plana: "S:/po-assets/gallery/二次元/蔚蓝档案/沙勒/普拉娜"
  Plana: "S:/po-assets/gallery/二次元/蔚蓝档案/沙勒/普拉娜"

  ## 阿拜多斯高级中学
  星野: "S:/po-assets/gallery/二次元/蔚蓝档案/阿拜多斯高级中学/小鸟游星野"
  小鸟游星野: "S:/po-assets/gallery/二次元/蔚蓝档案/阿拜多斯高级中学/小鸟游星野"
  大叔: "S:/po-assets/gallery/二次元/蔚蓝档案/阿拜多斯高级中学/小鸟游星野"
  hoshino: "S:/po-assets/gallery/二次元/蔚蓝档案/阿拜多斯高级中学/小鸟游星野"
  Hoshino: "S:/po-assets/gallery/二次元/蔚蓝档案/阿拜多斯高级中学/小鸟游星野"

  ## 千禧年科技学院
  aris: "S:/po-assets/gallery/二次元/蔚蓝档案/千禧年科技学院/游戏开发部/天童爱丽丝"
  Aris: "S:/po-assets/gallery/二次元/蔚蓝档案/千禧年科技学院/游戏开发部/天童爱丽丝"
  天童爱丽丝: "S:/po-assets/gallery/二次元/蔚蓝档案/千禧年科技学院/游戏开发部/天童爱丽丝"

  ## 崔尼蒂综合学院
  seia: "S:/po-assets/gallery/二次元/蔚蓝档案/崔尼蒂综合学院/茶会/百合园圣娅"
  圣娅: "S:/po-assets/gallery/二次元/蔚蓝档案/崔尼蒂综合学院/茶会/百合园圣娅"
  百合园圣娅: "S:/po-assets/gallery/二次元/蔚蓝档案/崔尼蒂综合学院/茶会/百合园圣娅"

  ## 歌赫娜学院
  ### 万魔殿
  枣伊吕波: "S:/po-assets/gallery/二次元/蔚蓝档案/歌赫娜学院/万魔殿/枣伊吕波"
  丹花伊吹: "S:/po-assets/gallery/二次元/蔚蓝档案/歌赫娜学院/万魔殿/丹花伊吹"

  ## 百鬼夜行联合学院
  桐生桔梗: "S:/po-assets/gallery/二次元/蔚蓝档案/百鬼夜行联合学院/桐生桔梗"

  ## 山海经高级中学
  kiki: "S:/po-assets/gallery/二次元/蔚蓝档案/山海经高级中学/龙华妃咲"
  kisaki: "S:/po-assets/gallery/二次元/蔚蓝档案/山海经高级中学/龙华妃咲"
  Kisaki: "S:/po-assets/gallery/二次元/蔚蓝档案/山海经高级中学/龙华妃咲"
  妃咲: "S:/po-assets/gallery/二次元/蔚蓝档案/山海经高级中学/龙华妃咲"
  龙华妃咲: "S:/po-assets/gallery/二次元/蔚蓝档案/山海经高级中学/龙华妃咲"
  门主: "S:/po-assets/gallery/二次元/蔚蓝档案/山海经高级中学/龙华妃咲"
  门主大人: "S:/po-assets/gallery/二次元/蔚蓝档案/山海经高级中学/龙华妃咲"

  ## 海兰德铁道学院
  橘光: "S:/po-assets/gallery/二次元/蔚蓝档案/海兰德铁道学院/橘光 & 橘望"
  橘望: "S:/po-assets/gallery/二次元/蔚蓝档案/海兰德铁道学院/橘光 & 橘望"
  铁道双子: "S:/po-assets/gallery/二次元/蔚蓝档案/海兰德铁道学院/橘光 & 橘望"

  # 崩坏：星穹铁道
  花火: "S:/po-assets/gallery/二次元/崩坏：星穹铁道/花火"
  Hanabi: "S:/po-assets/gallery/二次元/崩坏：星穹铁道/花火"
  hanabi: "S:/po-assets/gallery/二次元/崩坏：星穹铁道/花火"
  Sparkle: "S:/po-assets/gallery/二次元/崩坏：星穹铁道/花火"
  sparkle: "S:/po-assets/gallery/二次元/崩坏：星穹铁道/花火"
  ## 云璃
  云璃: "S:/po-assets/gallery/二次元/崩坏：星穹铁道/云璃"
  yunli: "S:/po-assets/gallery/二次元/崩坏：星穹铁道/云璃"
  Yunli: "S:/po-assets/gallery/二次元/崩坏：星穹铁道/云璃"

  ###################################### 三次元世界 ######################################
  日本古风: "S:/po-assets/gallery/三次元/日本古风"
  鞍马寺: "S:/po-assets/gallery/三次元/日本古风/鞍马寺"
  银山温泉: "S:/po-assets/gallery/三次元/日本古风/银山温泉"
  日本都市: "S:/po-assets/gallery/三次元/日本都市"

